### ISSUE TITLE
Why use path integrator instead of directlighting

### ISSUE THREAD

**Issue by elite-sheep** [lyfxyz/blsml#1]
I am very curious why you hacked the path integrator instead of direct lighting when you do an experiment on direct illumination sampling. Would it provide extra computation overhead or you have some other reasons?

**Comment by ethanleau** [comment]
The many-light method can be used for the next event estimation stage of any bounce (not just the bounce 0), so we do experiments on path integrator for flexibility.

**Comment by elite-sheep** [comment]
I tried a scene from Benedikt Bitteri's website with multi-bounce and the result had a lot of bias. I think there may be some bugs in this code base.
To repro this, please set the maxdepth to 4.
Ground Truth: https://benedikt-bitterli.me/resources/images/kitchen.png
Image: 
![image](https://user-images.githubusercontent.com/16146613/109506292-6e7ad380-7ad8-11eb-9969-57a82d54a1e7.png)
