### ISSUE TITLE
在vs2017上遇到的BSD问题

### ISSUE THREAD

**Issue by hugege1123** [lyfxyz/blsml#2]
大家好，我在vs2017上运行是这样的，出不来结果，而是一行字（如下），说是要BSD许可，应该咋怎么办呢？
pbrt version 3 (built Mar 29 2022 at 22:03:37) [Detected 8 cores]
*** DEBUG BUILD ***
Copyright (c)1998-2018 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
The source code to pbrt (but *not* the book contents) is covered by the BSD License.
See the file LICENSE.txt for the conditions of the license.

**Comment by ethanleau** [comment]
这行字总是会打印出来的，后面等一会不会出进度条吗？打的命令确定是下面这样吗？
./pbrt PATH2SCENE/cornell-box/scene.pbrt

**Comment by hugege1123** [comment]
输入了下面这样没反应，我在想是cmake编译的原因嘛
./pbrt PATH2SCENE/cornell-box/scene.pbrt

以下是cmake编译的结果。
fatal: not a git repository (or any of the parent directories): .git

fatal: not a git repository (or any of the parent directories): .git

Configuring done
Generating done

**Comment by ethanleau** [comment]
你程序编译了吗？有可执行文件吗？

**Comment by hugege1123** [comment]
编译了，也运行了，运行之后就在cmd上出现下面这些文字，输入./pbrt PATH2SCENE/cornell-box/scene.pbrt没反应
pbrt version 3 (built Mar 30 2022 at 15:57:41) [Detected 8 cores]
Copyright (c)1998-2018 Matt Pharr, Greg Humphreys, and Wenzel Jakob.
The source code to pbrt (but *not* the book contents) is covered by the BSD License.
See the file LICENSE.txt for the conditions of the license.

**Comment by ethanleau** [comment]
输入的目录是指向scene.pbrt吗？”PATH2SCENE“只是一个示例

**Comment by hugege1123** [comment]
你好，我是有一个bisml-master文件夹，此文件夹里面有scene和build文件夹。
运行之后是的exe文件是D:\liulanqi_downloaded\bisml-master\build\Release\pbrt.exe
我应该怎么输入指令才可以执行呢？

**Comment by ethanleau** [comment]
在Release目录输入：
`./pbrt.exe ..\..\scene\cornell-box\scene.pbrt`

**Comment by hugege1123** [comment]
你好，很感谢您在百忙之中街道我的问题！我已经解决！

**Comment by hugege1123** [comment]
你好，很感谢您在百忙之中解答我的问题！问题已经解决！非常感谢！
